### ISSUE TITLE
Plans to support Report Slave ID (FC17) ?

### ISSUE THREAD

**Issue by vshymanskyy** [yaacov/node-modbus-serial#113]
Thanks for a great library.
Are there any plans to support Report Slave ID (FC17) ?
I think I will try implementing it in a local copy and then make a PR - but i may need your help if I run into some issues.
Also, some hardware implements completely custom FCs - is there any way to handle them without modbus-serial modifications?

**Comment by yaacov** [comment]
> Are there any plans to support Report Slave ID (FC17) ?

If you implement it :-)

> some hardware implements completely custom FCs

Sounds cool to make some way to register new / cusrom FC 👍 , maybe convert current regular FC to use this new ? `register_FC` ? architecture ?

**Comment by yaacov** [comment]
Closing, do not have time to implement this now ... may open if I have time.
