### ISSUE TITLE
connectTcpRTUBuffered always timeout

### ISSUE THREAD

**Issue by xalepo4** [yaacov/node-modbus-serial#117]
Hello, 
I'm working with this library but when I use the server.js and then buffertcp.js it always give me timeout.
If I replace connectTcpRTUBuffered for connectTCP it works well, but I need the other function.
Any assistance would be greatly appreciated.

**Comment by yaacov** [comment]
@xalepo4 hi, thanks for the issue, I will look into it this weekend.

If you can post example code that reproduce this, it will be easier to find the problem.

**Comment by xalepo4** [comment]
This is the server I'm running:

`/* eslint-disable no-console, no-unused-vars, spaced-comment */

// create an empty modbus client
//var ModbusRTU = require("modbus-serial");
var ModbusRTU = require("../index");
var vector = {
    getInputRegister: function(addr) { return addr; },
    getHoldingRegister: function(addr) { return addr + 8000; },
    getCoil: function(addr) { return (addr % 2) === 0; },
    setRegister: function(addr, value) { console.log("set register", addr, value); return; },
    setCoil: function(addr, value) { console.log("set coil", addr, value); return; }
};

// set the server to answer for modbus requests
console.log("ModbusTCP listening on modbus://0.0.0.0:8502");
var serverTCP = new ModbusRTU.ServerTCP(vector, { host: "0.0.0.0", port: 8502, debug: true, unitID: 1 });`

And this is the client:

`/* eslint-disable no-console, spaced-comment */

// create an empty modbus client
//var ModbusRTU = require("modbus-serial");
var ModbusRTU = require("../index");
var client = new ModbusRTU();

// NPort Gateway 801D NetPort
client.connectTcpRTUBuffered("127.0.0.1", { port: 8502, removeCrc: false })
    .then(setClient)
    .then(function() {
        console.log("Connected");
    })
    .catch(function(e) {
        console.log(e.message);
    });

function setClient() {
    // set the client's unit id
    // set a timout for requests default is null (no timeout)
    client.setID(1);
    client.setTimeout(2000);

    // run program
    run();
}

function run() {
    // read the 4 registers starting at address 5
    client.readHoldingRegisters(5, 4)
        .then(function(d) {
            console.log("Receive:", d.data);
        })
        .catch(function(e) {
            console.log(e.message);
        })
        .then(close);
}

function close() {
    client.close();
}`

**Comment by xalepo4** [comment]
This is the server I'm running:
https://github.com/yaacov/node-modbus-serial/blob/master/examples/server.js
And this is the client:
https://github.com/yaacov/node-modbus-serial/blob/master/examples/buffertcp.js

**Comment by yaacov** [comment]
Hi, this tests run fine on my machine, do I miss something:

![node](https://user-images.githubusercontent.com/2181522/27081018-3b0a39ec-5047-11e7-9d81-1fe357502e5d.png)

**Comment by xalepo4** [comment]
I've try it again and this is the result:
Client.js
![captura de pantalla 2017-06-13 a las 14 58 55](https://user-images.githubusercontent.com/11753212/27083456-e3873ab0-5048-11e7-9a69-d945b115c0f6.png)
Server.js
![captura de pantalla 2017-06-13 a las 14 58 49](https://user-images.githubusercontent.com/11753212/27083467-f140452a-5048-11e7-9fca-1e1407beeab5.png)
And this is the output:
Client.js
![captura de pantalla 2017-06-13 a las 15 00 10](https://user-images.githubusercontent.com/11753212/27083495-0906b69e-5049-11e7-8219-ec87eaa09670.png)
Server.js
![captura de pantalla 2017-06-13 a las 15 00 10](https://user-images.githubusercontent.com/11753212/27083501-0ed44dd4-5049-11e7-98c7-86a0c71afea3.png)

**Comment by yaacov** [comment]
can you check the version you use ?

`npm view modbus-serial version`

**Comment by xalepo4** [comment]
Version 5.3.1

**Comment by yaacov** [comment]
can you try ?

`npm install modbus-serial@5.2.9`

**Comment by xalepo4** [comment]
It works!!

**Comment by yaacov** [comment]
Thanks for the Issue ! 
I will try to see what is wrong with the new version this weekend.

not closing this issue, until it is fixed in the new version.

p.s.
@checor we may have a bug in newer versions, can you try v5.2.9 ?

**Comment by yaacov** [comment]
fixed by #123
