### ISSUE TITLE
Shouldn't serialport be an optional dependency?

### ISSUE THREAD

**Issue by vshymanskyy** [yaacov/node-modbus-serial#118]
Also, Modbus RTU may be transported over virtually any streaming connection, like sockets or bluetooth (BLE) ,etc.

**Comment by yaacov** [comment]
Yes, it was :-)

But we wanted to make it easy for users to just have one requirement,
See: https://github.com/yaacov/node-modbus-serial/issues/56

I'm inclining to remove this dependency ( we do not enforce it in the code ... [1] ) but I also want users to have easy life ...

[1] https://github.com/yaacov/node-modbus-serial/blob/master/index.js#L656

**Comment by vshymanskyy** [comment]
Cool. Thanks for explanation!
How about just being able to work with any Node.js stream: https://nodejs.org/api/stream.html
SerialPort already supports that and they improve it further in release 5+

**Comment by yaacov** [comment]
> How about just being able to work with any Node.js stream:

sound great, can you make a pull request ?

**Comment by vshymanskyy** [comment]
Probably - when I get to it ;)

**Comment by yaacov** [comment]
> Probably - when I get to it ;)

have fun =^..^=

**Comment by yaacov** [comment]
Closing, as I do not have time to look at it now.

**Comment by emes** [comment]
Would you re-consider making serialport an optional dependency?  Docker images become muuuch larger when serialport needs to be built from source, which is shame when using only tcp.

**Comment by yaacov** [comment]
@ems Thank you for this issue :+1: 

a - it's still optionals in the code: https://github.com/yaacov/node-modbus-serial/blob/master/index.js#L738

b - I think the only problem is only here https://github.com/yaacov/node-modbus-serial/blob/master/package.json#L41

c- Can you think of a mechanism that will keep the default, **and** let us an option to build leaner containers ?
e.g. `package-no-serial-port.json`, `pckage.json.template` build with some Makefile ... ?

p.s. you can send a pull request with the dockerfile if you think it's nice :-)
