### ISSUE TITLE
TCP Server give differents responses each time

### ISSUE THREAD

**Issue by xalepo4** [yaacov/node-modbus-serial#119]
Hi,
I'm using version 5.2.9 and I've found another extrange think.
If I execute the example TCP server and execute another script using the function readCoils for example it give me differents results everytime. If I execute readHoldingRegisters as in your tests it answer me ok, but only that function works correctly.
I attach my code and screenshots:

Server.js:
![test1](https://user-images.githubusercontent.com/11753212/27177124-94740722-51c5-11e7-81e5-766ada625ffe.png)

Client.js
![test](https://user-images.githubusercontent.com/11753212/27177133-9bfc9fae-51c5-11e7-956e-5180c0154c8e.png)

Output with debug activated:
![terminal](https://user-images.githubusercontent.com/11753212/27177150-a4122e98-51c5-11e7-81ba-fe25aa13f1f6.png)

**Comment by yaacov** [comment]
Thanks ! I will look into it

**Comment by xalepo4** [comment]
I'm looking the code and testing and in servertcp.js when you create a buffer you use new Buffer(size) instead of new method Buffer.alloc(size). If you print the buffer before create with the old method it have random values.

**Comment by xalepo4** [comment]
Tested changing new Buffer(size) to Buffer.alloc(size) and it works fine

**Comment by yaacov** [comment]
Can you make a pull request ?

**Comment by xalepo4** [comment]
Yes this afternoon I'll make.

**Comment by yaacov** [comment]
Fixed in https://github.com/yaacov/node-modbus-serial/pull/120

Thanks @xalepo4
