### ISSUE TITLE
Modbus TCP Write

### ISSUE THREAD

**Issue by IlhanSeven** [yaacov/node-modbus-serial#126]
Thank you for sharing this. This has been very useful. I don't know if this functionality is implemented but Modbus TCP write gives:

{ name: '', message: 'Port Not Open', errno: 'ECONNREFUSED' }

Port is actually open because I am reading values via Modbus TCP. I wonder if it means 'Serial Port' when it says 'Port Not Open'.

**Comment by yaacov** [comment]
Thanks for the issue, can you put here a sample program that show this ?

**Comment by IlhanSeven** [comment]
Thanks for quick replay. The issue is timing as I found.
Below says 'Port Not Open'
...
client.connectTCP('192.168.1.68', { port: 5502 });
client.setID(1);
client.writeRegisters(5, [5, 6, 7]);
...

Below is ok.
...
client.connectTCP("192.168.1.68", { port: 5502 })
    .then(setClient);

function setClient() {
    client.setID(1);
    write();
}

function write() {
    client.writeRegisters(5, [5, 6, 7]);
}

**Comment by yaacov** [comment]
Closing ?

**Comment by IlhanSeven** [comment]
Yes, Thanks again.

**Comment by yaacov** [comment]
np :-)
