### ISSUE TITLE
servertcp.js  function _handleForceMultipleCoils - value is always true

### ISSUE THREAD

**Issue by Thosty** [yaacov/node-modbus-serial#127]
Hi

I think the expression `state !== 0` is not correct because in my case the value of a coil is always true. 

Kind regards

**Comment by yaacov** [comment]
Nice 👍 , can you write a pull request changing it to `!== false` ?

**Comment by Thosty** [comment]
I will try it. I've never done that before 😊.

**Comment by yaacov** [comment]
have fun.

first check that this really fix the problem ... :-)

**Comment by yaacov** [comment]
Fixed by https://github.com/yaacov/node-modbus-serial/pull/128

Do you need it in the npm package, or this can wait for a new release ?

**Comment by Thosty** [comment]
This can wait for a new release.

**Comment by yaacov** [comment]
👍
