### ISSUE TITLE
pulling out crc16 has broken response check

### ISSUE THREAD

**Issue by dom-white** [yaacov/node-modbus-serial#13]
The new single crc16 function works for appending to requests, but fails when checking responses as it no longer skips the last two bytes i.e. the crc of the response packet.

The crc version when checking repsonses included this extra line, then referenced 'length' for the for loop rather than buf.length

var length = buf.length - 2;

**Comment by dom-white** [comment]
Could be fixed by passing in a slice of the buffer as per the request side
crc16(buf.slice(0, -2))
rather than
crc16(buf)
in the ports checkData method

**Comment by dom-white** [comment]
I've sent a pull request which I think fixes the issue.
It was fine on the test port, but not on the serial,tcp,udp ports

**Comment by dom-white** [comment]
Closing as pull request now merged in.

**Comment by connium** [comment]
Obviously missed some parts when cherry-picking from another branch. Damn!
Thanks @dom-white for spotting and fixing this!

**Comment by yaacov** [comment]
:+1:  sorry for not checking before merging.
