### ISSUE TITLE
RTU port close

### ISSUE THREAD

**Issue by BrkDalkiran** [yaacov/node-modbus-serial#133]
how to close a serial port?

var ModbusRTU = require("modbus-serial");
 var rtuClient = new ModbusRTU();
                    rtuClient.connectRTUBuffered('/ttyUSB0', {
                        baudrate: 9600,
                        parity: 1,
                        dataBits: 8,
                        stopBits: 1
                    }) .then(function () { });

**Comment by yaacov** [comment]
`rtuClient.close()`

https://github.com/yaacov/node-modbus-serial/blob/master/index.js#L345
