### ISSUE TITLE
set vmin parameter to MIN_MODBUS_PACKET

### ISSUE THREAD

**Issue by ReinierH** [yaacov/node-modbus-serial#135]
Hi!

I noticed that the library is trying to parse 1 byte frames. setting the vmin to MIN_MODBUS_PACKET would solve this problem preventing the parser from parsing invalid packets.

**Comment by yaacov** [comment]
Nice !  can you make a pull request ?

**Comment by ReinierH** [comment]
Working on it

**Comment by yaacov** [comment]
fixed by #136
