### ISSUE TITLE
response delay for server?

### ISSUE THREAD

**Issue by biancode** [yaacov/node-modbus-serial#144]
Dear yaacov,

it is helpful for testing to work with an optional response delay for the server.
With that, I can setup a server with a variety, long or short delay.

_parseModbusBuffer -> return with setTimeout of responseDelay?

cya Klaus

**Comment by yaacov** [comment]
sounds good to me :-)

**Comment by yaacov** [comment]
@biancode hi,

belated happy new year :-)

can you check if latest pull requests (#170 #172 #173 #174 #175 and #176) fix this ?

**Comment by yaacov** [comment]
reference: https://github.com/yaacov/node-modbus-serial/issues/163

**Comment by yaacov** [comment]
Fixed by #170 .. #176
