### ISSUE TITLE
serialport isOpen to Boolean - is not a function

### ISSUE THREAD

**Issue by biancode** [yaacov/node-modbus-serial#149]
I did not see port.isOpen - [Serialport](https://github.com/EmergingTechnologyAdvisors/node-serialport/blob/master/test/serialport.js) line 219 test - is now Boolean not a function

**Comment by biancode** [comment]
hint for me - Serialport should be wrapped to hold a static own API

**Comment by biancode** [comment]
@yaacov what do you say - change isOpen to Boolean in that lib or build a wrapper for SerialPort to be compatible

**Comment by yaacov** [comment]
> @yaacov what do you say - change isOpen to Boolean in that lib or build a wrapper for SerialPort to be compatible

I prefer to change isOpen to Boolean like:
https://github.com/EmergingTechnologyAdvisors/node-serialport/commit/5616664ed67a983a28aa54e08350f374e9be9085

**Comment by yaacov** [comment]
@biancode hi,

We have a new version v6.0.1 that fixs this 🎉 🍰 
Can you check that it fixes this issue ?

**Comment by biancode** [comment]
@yaacov - yes I'll check it tomorrow - thank you!

**Comment by biancode** [comment]
@yaacov it works very well for me and for now, I'm very happy with that version

If you find some time try your Modbus server in Node-RED

![image](https://user-images.githubusercontent.com/4369867/31099604-dd91ac00-a7c6-11e7-87d6-af6def70b82b.png)

**Comment by yaacov** [comment]
> it works very well for me
