### ISSUE TITLE
baudrate or baudRate

### ISSUE THREAD

**Issue by neldefant** [yaacov/node-modbus-serial#152]
The documentation for node serialport (5.0.0) uses "baudRate" - capital "R" for the optional parameter. In practice, at least on windows, this seems to matter. The examples use the default of 9600, so it is possible that the "baudrate" parameter is being ignored and things just happen to work.

![image](https://user-images.githubusercontent.com/17005294/31230705-b03e7e0a-a9dc-11e7-9f68-dcaa5ce2f951.png)

If this isn't  misunderstanding on my part, I'll fix it.

**Comment by yaacov** [comment]
Thanks !

https://github.com/EmergingTechnologyAdvisors/node-serialport#module_serialport--SerialPort..openOptions
