### ISSUE TITLE
serialport should be min v6.0.4

### ISSUE THREAD

**Issue by biancode** [yaacov/node-modbus-serial#159]
Dear yaacov,

see [Issue](https://github.com/biancode/node-red-contrib-modbus/issues/61) early serialport versions has CPU load, which is fixed if the test is running with v6.0.4 of serialport package

Happy coding!
Klaus

**Comment by yaacov** [comment]
can you make a pull request ?

**Comment by biancode** [comment]
Yes sure, but what about v7.0.0 is it ready to use?

**Comment by yaacov** [comment]
> Yes sure, but what about v7.0.0 is it ready to use?

Yes :-)

The changes where too small, so I waited with publishing a new release, It include the needed change from boudrate to baudRate, and the open issues are not blockers.

**Comment by yaacov** [comment]
closed by #160

**Comment by yaacov** [comment]
@biancode v7.0.1 is on npm 🍰
