### ISSUE TITLE
No support for v8 node.js

### ISSUE THREAD

**Issue by dom-white** [yaacov/node-modbus-serial#166]
Sometime ago an 'engine' limitation was added to this repo to prevent node-modbus-serial running with anything other than node.js v4 or v6. See following commit:

[update to new serialport with better listing of ports - supports just LTS versions like 4 and 6 later 8 and so on](https://github.com/yaacov/node-modbus-serial/commit/79a8697b22e528cc2a9fdd77ab65f6c826eee3b0#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)

As of October 2017, v8 is the latest LTS version of node.js

Is it possible to add v8 to the list of acceptable engines, or to remove the limitation?

The npm package manager seems to ignore this 'engine' parameter, but I install using yarn which does take it into account, and you will get the following error if you attempt to install using an 'incompatible' version:

`error modbus-serial@7.0.1: The engine "node" is incompatible with this module. Expected version "4.x || 6.x".`

Ideally I would remove this restriction as it is just another thing that requires maintaining/updating. Plus I am not sure why such a strict enforcement policy is really required (especially one that is ignored by some package managers). I run v7 currently (for various reasons, with a plan to move to v8 shortly) and so I would not be able to use the latest version of modbus without forking and patching.

Wouldn't a 'tested with version x and y' statement in the readme suffice?

Thanks
Dominic

**Comment by yaacov** [comment]
> Is it possible to add v8 to the list of acceptable engines, or to remove the limitation?

my vote - remove the limitation :-) 

> Wouldn't a 'tested with version x and y' statement in the readme suffice?

my vote - yes

can you make a pull request removing this check, and add some notice in the readme ?

**Comment by yaacov** [comment]
fixed by #167
