### ISSUE TITLE
Modbus exception 4 with 7.1.3

### ISSUE THREAD

**Issue by biancode** [yaacov/node-modbus-serial#179]
Hi @yaacov ,

<img width="1101" alt="grafik" src="https://user-images.githubusercontent.com/4369867/35888400-c6140412-0b97-11e8-9f2a-71cb75d5428b.png">

all as before but now exception ... it is a test with positive and negative values

<img width="889" alt="grafik" src="https://user-images.githubusercontent.com/4369867/35889224-efddb880-0b9a-11e8-9aa0-666e9503c249.png">

I will test more the next few days, but maybe you see some to give a hint ...

cya
Klaus

**Comment by biancode** [comment]
FC5 and FC16 works well, but FC6 doesn't

**Comment by yaacov** [comment]
maybe:
https://github.com/yaacov/node-modbus-serial/blob/master/servers/servertcp.js#L510

should be:
`callback(null, responseBuffer);`
instead of:
`callback(responseBuffer);`
?

**Comment by biancode** [comment]
Yes, that is the problem.

**Comment by yaacov** [comment]
fixed by #180

**Comment by yaacov** [comment]
@biancode 7.1.4 is out 🎆
