### ISSUE TITLE
Set a bit of an holding register

### ISSUE THREAD

**Issue by robertsLando** [yaacov/node-modbus-serial#187]
I have been unable to find a modbus TCP server/slave with FC 22 and 23 implemented so far. The goal of FC22 is to be able to write to holding registers single bit as in the PLC world for example %MW1.1

> The MODBUS service FC22 “Mask write” is a register service that makes it possible to specifically change bits in a register.

Any hint if it already exists or I will have to implement this myself ? 

The alternative is to implement it by creating a function like 'setRegisterBit(reg, bitIndex, bitValue, callback)` that make 2 operations:

- Read register `reg`
- Convert the value read :

```
value = value.toString(2);
value = value.length < 16 ? '0'.repeat(16-value.length) + value : value;
value = value.split('').reverse();
value[bitIndex] = bitValue;
value = value.reverse().join('');
value = parseInt(value, 2);
```

- Write the value as uint using FC 6

What about this feature?

**Comment by yaacov** [comment]
we currently support:
https://github.com/yaacov/node-modbus-serial/blob/master/index.js#L310
https://github.com/yaacov/node-modbus-serial/blob/master/servers/servertcp.js#L109

I am not against supporting extra FC's, you are welcome to add a pull request that adds this functionality.

**Comment by robertsLando** [comment]
FC 22 is really poorly supported so I think I will go for the second alternative.
