### ISSUE TITLE
CRC error on readInputRegisters

### ISSUE THREAD

**Issue by Athiththan** [yaacov/node-modbus-serial#188]
I have been started working on reading multiple input registers from energy meters. I am getting an error on CRC check Failed when connecting and reading Input Registers ... (Still a beginner)

What will be the issue 

please help me, thanks in advance

**Comment by yaacov** [comment]
Hi, thanks for the issue,
Can you post the code that fails ?

**Comment by Athiththan** [comment]
setInterval(() => {
    master.readInputRegisters(config.Address, config.Length, (err, data) => {
        if (err)
            console.error(colors.red.bold("Modbus Read Input Registers Error | Exception: " + err));
        else {
            console.log(data);
        }
    });
}, timeOut.timeout);

this is the part of the portion i am working on it

**Comment by yaacov** [comment]
where did `master` come from ?

**Comment by Athiththan** [comment]
const modbusSerial = require('modbus-serial');
const master = new modbusSerial();
master.connectRTU(config.Port, {
    baudRate: config.BaudRate,
    dataBits: config.DataBits,
    stopBits: config.StopBits,
    parity: config.Parity
});

//stopBits: config.StopBits
//rtscts: true

master.setID(config.SlaveID);

**Comment by yaacov** [comment]
try `connectRTUBuffered` instead of `connectRTU`

**Comment by Athiththan** [comment]
if i use `connectRTUBuffered` it outputs none

**Comment by yaacov** [comment]
do you have good readings using other modbus client ?

**Comment by Athiththan** [comment]
Yes the same code worked for 2 other energy meters from another vendor. This meter is different from the others 2 so i tried all the possible ways to connect to it. But it throws me the Exception of CRC failed

**Comment by yaacov** [comment]
sounds like the meter is faulty

**Comment by Athiththan** [comment]
or is it regarding any bit arrangement

**Comment by Athiththan** [comment]
Thank you ... for the quick responses bro
