### ISSUE TITLE
serialport 6.1.1 works much better on Mac

### ISSUE THREAD

**Issue by biancode** [yaacov/node-modbus-serial#190]
Hi yaacov,

serialport 6.1.1 works much better on Mac for me - maybe you find some time to upgrade.
v6.0.5 has some problems on macOS

cya
Klaus

**Comment by yaacov** [comment]
:+1:  I will look at it next weekend.

Can you check if using 6.1.1 "just work" , so we can just update package.json ?

**Comment by biancode** [comment]
Yes, I'll check it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by biancode** [comment]
I got an information to test more with windows and the serialport list of ports.
