### ISSUE TITLE
problem with modbus-serial: SerialPort is not defined

### ISSUE THREAD

**Issue by cpfarher** [yaacov/node-modbus-serial#201]
Hello, I am trying to use modbus-serial but I get an error when I try to use on chrome browser:

I get VM1320:1 Uncaught ReferenceError: SerialPort is not defined on line: ./node_modules/modbus-serial/apis/connection.js?5f16
this._port = new SerialPort(path, options);

node v10.1.0
"modbus-serial": "^7.2.2",
"serialport": "^6.2.0",

If I used it in bash console with node command, all was ok... 
any help?

**Comment by yaacov** [comment]
Hi, thanks for the question.

The `modbus-serial` package use the `serialport` package  [[1](https://www.npmjs.com/package/serialport)] that does not work on browsers [[2](https://www.npmjs.com/package/serialport#platform-support)].

If you want, you can add support for using `browser-serialport` package  [[3](https://www.npmjs.com/package/browser-serialport)] , it should work exactly as the node `serialport` one ( but for browsers :-) ).

[1] https://www.npmjs.com/package/serialport
[2] https://www.npmjs.com/package/serialport#platform-support
[3] https://www.npmjs.com/package/browser-serialport
