### ISSUE TITLE
How to set parity？

### ISSUE THREAD

**Issue by Simple-yzp** [yaacov/node-modbus-serial#202]
hi,How to set parity？I did not find the relevant documentation，think you

**Comment by yaacov** [comment]
Hi, thanks for the question.

modbus serial use serialport [1] for seria comunication, it passes to serial port the `openOptions` hash [2].

For example:
```
client.connectRTUBuffered("/dev/ttyUSB0", { baudRate: 9600, parity: 'even' });
```

[ defaults are: 9600,8,N,1 ]


[1] https://github.com/node-serialport/node-serialport
[2] https://node-serialport.github.io/node-serialport/global.html#openOptions

**Comment by yaacov** [comment]
@Simple-yzp 
If it worked, you can close this issue, if not we can look at it in more detail ...
