### ISSUE TITLE
[Question] Close connections or keep them open?

### ISSUE THREAD

**Issue by dushyantbangal** [yaacov/node-modbus-serial#208]
I'm gathering data from a couple of devices every minute.

Right now I connect to all the devices when the script starts, and then call the read functions every 60 seconds.
I'm not closing the connection, I'm reusing the same connection.

Should I be closing connections on every read and then opening again the next minute?

**Comment by yaacov** [comment]
Hi, thanks for the question :+1: 

> Should I be closing connections on every read and then opening again the next minute?

That depends on the specifics ... 
a. Open and Close a connection may take resources, so it may be better not to close/open unless we have an error that require a reconnect.
b. On the other hand, an open connection blocks other masters from queering the device (if using TCP) so closing the connection each time may free resources.

You should check the specific way you use the connection and close or not close depending on how you use it.
