### ISSUE TITLE
Different callbacks for FC1 and FC2

### ISSUE THREAD

**Issue by debevv** [yaacov/node-modbus-serial#212]
Hi, I noticed that the server library uses the same `getCoil` callback whenever it gets a FC1 or FC2 request.
This is a bit inconvenient when writing a simulator, because one would have two different blocks of memory for coils and discrete inputs, but now there's no way to distinguish (or yes?) which block we want to read from when inside the `getCoil` callback.
So my request would be adding another callback which targets only the FC2 request. I can send you a PR if you want, but I wanted to discuss the issue first.

**Comment by yaacov** [comment]
> So my request would be adding another callback which targets only the FC2 request. I can send you a PR if you want, but I wanted to discuss the issue first.

Sounds great !, can you make a pull request ?
