### ISSUE TITLE
about timeout

### ISSUE THREAD

**Issue by fly19890211** [yaacov/node-modbus-serial#22]
Hello, thanks for this module :)
and i'm using connectRTUBuffered, is there timeout for this api? 

Thanks

**Comment by yaacov** [comment]
Hi, thanks, it use the serialport module, timeout is a property of the serial port ...
https://github.com/voodootikigod/node-serialport
can you ask there ?

**Comment by fly19890211** [comment]
Hi,
ok. i will do that, thanks.

**Comment by yaacov** [comment]
Hi, did you found how solve the problem ?

**Comment by fly19890211** [comment]
hello, thanks for replying.
actually, i can't find the how to solve the problem...

**Comment by yaacov** [comment]
can you explain what is your use case / what you are trying to do ?
maybe their is a way to solve you problem, that does not involve timeouts ?

**Comment by fly19890211** [comment]
my case is i use it for reading inverters of solar energy station. and sometimes the inverter doesn't respond, so i need to timeout to escape the connectRTUBuffered.
Thank you.

**Comment by yaacov** [comment]
hi, thanks for answering

take a look at:
https://github.com/yaacov/node-modbus-serial/blob/master/examples/watchdog.js

1. it's tcp but it should work on rtu.
2. we have a new `close` method :tada: , so you can also close the connection and reconnect if you want.

**Comment by yaacov** [comment]
Fixed by: https://github.com/yaacov/node-modbus-serial/pull/26

**Comment by fly19890211** [comment]
Thanks, really appreciate for this updating. 
can you please update the Readme.md about how to use timeout.

**Comment by yaacov** [comment]
> can you please update the Readme.md about how to use timeout.

https://github.com/yaacov/node-modbus-serial/blob/master/examples/watchdog.js
