### ISSUE TITLE
no issue

### ISSUE THREAD

**Issue by vipulpatel1994** [yaacov/node-modbus-serial#228]
Sorry for rising here, not getting any option to contact you.
Where exactly can we use this?
I have one modem which can connect to TCP/IP. need to send one hex string(01 04 00 01 00 01 60 0A) to get data after connection. able to connect but not able to send back hex can you help me out.

**Comment by yaacov** [comment]
Hi thanks for the issue,

This vary from device to device, you will need to consult with the modem manual, and the docs for the software you use.

**Comment by vipulpatel1994** [comment]
Thanks a lot for help @dushyantbangal and @yaacov  . for now done with custom code. I will surely try this.

**Comment by yaacov** [comment]
> for now done with custom code.

:smiley: 

@vipulpatel1994 closing. feel free to open a new issue if needed.
