### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by paradigminversion** [yaacov/node-modbus-serial#229]
I'm using:
>node -v
v10.2.1
>uname -a
Linux beaglebone 4.4.54-ti-r93 #1 SMP Fri Mar 17 13:08:22 UTC 2017 armv7l GNU/Linux
"modbus-serial": "^7.2.3"

After about a minute of polling a device, I get the following error:

[[17:11:23.651]] [ERROR] (node:9974) UnhandledPromiseRejectionWarning: #<TransactionTimedOutError>
[[17:11:23.657]] [ERROR] (node:9974) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[[17:11:23.661]] [ERROR] (node:9974) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by yaacov** [comment]
@paradigminversion Thanks for the issue !

**Comment by paradigminversion** [comment]
Resolved...It was a re-entrancy issue on my serial port handle.  It works now that I protect it with a semaphore.
