### ISSUE TITLE
Module fails to build via TypeScript

### ISSUE THREAD

**Issue by ericbarch** [yaacov/node-modbus-serial#243]
Greetings!

It appears that the latest release (7.4.1) no longer compiles properly under TypeScript. My projects that use modbus-serial now fail with:

`node_modules/modbus-serial/ServerTCP.d.ts:1:8 - error TS1192: Module '"events"' has no default export.`

Note that I am actually using ModbusRTU with the default export: `import ModbusRTU from 'modbus-serial';`.

**Comment by yaacov** [comment]
@ericbarch can you look at:

https://github.com/yaacov/node-modbus-serial/pull/239#issuecomment-430650820

Is it related to your problem ?

**Comment by ericbarch** [comment]
Just opened PR #244. This should fix it 😃

**Comment by ericbarch** [comment]
I did take a look at #239, but I am using the default export (which works fine). The issue reported here is related to incorrect syntax of an ES6 import via TypeScript.

**Comment by yaacov** [comment]
closed via #244
