### ISSUE TITLE
FC16 handling and Remote Address

### ISSUE THREAD

**Issue by tizl1234** [yaacov/node-modbus-serial#247]
Hi,
I have two questions:
 1) How can I handle FC16 on modbus TCP server? If I use such code [example](https://jsfiddle.net/tizl1234/5ofn1ytx/3/) I receive values one by one. It's not apliable in my case. It would be better if i could receive values in array format. Maybe there is a way to do that in this module?
2) How can I receive remote address of slave device in my serverTCP vector?

Thank you!

**Comment by yaacov** [comment]
> How can I handle FC16 on modbus TCP server? If I use such code example I receive values one by one. It's not apliable in my case. It would be better if i could receive values in array format. Maybe there is a way to do that in this module?

No, the function that implement multiple write is here, it just loop over the values and call the single-set method:
https://github.com/yaacov/node-modbus-serial/blob/master/servers/servertcp_handler.js#L602

Multiple reads **are** implemented, you can look at the code that handle multiple reads here:
https://github.com/yaacov/node-modbus-serial/blob/master/servers/servertcp_handler.js#L221
https://github.com/yaacov/node-modbus-serial/blob/master/servers/servertcp_handler.js#L255

You can make a pull request that does the same thing for the write method.

> How can I receive remote address of slave device in my serverTCP vector?

No,

The function that calls the server vector methods is:
https://github.com/yaacov/node-modbus-serial/blob/master/servers/servertcp.js#L125

You can add the remote adress when calling it:
https://github.com/yaacov/node-modbus-serial/blob/master/servers/servertcp.js#L271

using:
https://github.com/yaacov/node-modbus-serial/blob/master/servers/servertcp.js#L218

and then propagate it to the vector calls.

Will be happy to here if that helped, have fun.
