### ISSUE TITLE
read and write simultaneosly

### ISSUE THREAD

**Issue by accateo** [yaacov/node-modbus-serial#255]
Hi,
it's possible to write and "read" simultaneosly?
For example, I would use a timer that, every seconds, call an "writeFC1" and another timer that, every 5 seconds, call an "writeFC5".
Maybe on the same register?
Thanks

**Comment by yaacov** [comment]
Not If you use a serial line, somewhere.

a - if you know that that all connections from your client to the device are all TCP you can do parallel communication over tcp modbus.
b - if you have serial line on the path ( can also be some tcp to serial converter somewhere on the path,  even if it's TCP on you end ) you can not use parallel communication using modbus.

**Comment by accateo** [comment]
Thank you!
