### ISSUE TITLE
ModbusRTU.ServerTCP on connection event 

### ISSUE THREAD

**Issue by onur2677** [yaacov/node-modbus-serial#269]
i can't see on wiki , is there a config for "connected" event  ? 🙏

**Comment by yaacov** [comment]
Hi, thanks for the issue :+1: 

Not sure what the question is ?
Can you give an example.

**Comment by onur2677** [comment]
Hi !

for example;

```js
var serverTCP = new ModbusRTU.ServerTCP(options)

serverTCP.on('connect', function (err) {

})

```

**Comment by yaacov** [comment]
IIUC no, see:
https://github.com/yaacov/node-modbus-serial/blob/master/servers/servertcp.js#L218

When `ServerTCP(options)` have a connection, we immediately start listening for "data".

**Comment by yaacov** [comment]
Also see:
https://github.com/yaacov/node-modbus-serial/blob/master/examples/server.js

**Comment by onur2677** [comment]
hmm ok i got it. thanks for answering my question.  :pray:

**Comment by yaacov** [comment]
np, have fun :white_flower:
