### ISSUE TITLE
is it able to use "MODBUS SERIAL LINE PDU" over TCP

### ISSUE THREAD

**Issue by chess99** [yaacov/node-modbus-serial#274]
"MODBUS SERIAL LINE PDU" means exact this structure : 
Server address (1 byte) + MODBUS PDU + CRC (2 bytes)

**Comment by yaacov** [comment]
Hi, thanks for the issue :heart:

> "MODBUS SERIAL LINE PDU" means exact this structure :
Server address (1 byte) + MODBUS PDU + CRC (2 bytes)

What do you mean, what should be fixed ?!

**Comment by chess99** [comment]
I think I find what I want from #43 

I just want to use modbus-RTU over TCP connection
"connectTelnet " doing exactly what I want

thanks anyway
