### ISSUE TITLE
Unable to install the module

### ISSUE THREAD

**Issue by codyc1515** [yaacov/node-modbus-serial#299]
I am unable to install the module. I'm running node v13.0.1 with npm v6.12.0.

The command I am using is `sudo npm install -g --unsafe-perm --build-from-source modbus-serial`.

Logs & errors: https://gist.github.com/codyc1515/cf80a4264142734a328947b429677632

**Comment by yaacov** [comment]
a - try installing without serialport `sudo npm install -g modbus-serial@7.7.3-no-serial-port`
b - look for a way to install `serialport` on your system: https://serialport.io/docs/guide-platform-support

if you succeed in installing `serialport` try to understand why it can't install as a dependency of modbus-serial, we may be able to fix that.

**Comment by yaacov** [comment]
@codyc1515 ?

**Comment by yaacov** [comment]
closing, stale
