### ISSUE TITLE
Add Modbus UDP

### ISSUE THREAD

**Issue by Ekristoffe** [yaacov/node-modbus-serial#306]
Hello, in some case we need to use Modbus over UDP connection (it work exactly like the Modbus TCP but using UDP.
Is it possible to also have a Modbus UDP function ?
Thanks

**Comment by yaacov** [comment]
Sure :+1:

Look at the ports dir - https://github.com/yaacov/node-modbus-serial/tree/master/ports

You can take the tcpport [ https://github.com/yaacov/node-modbus-serial/blob/master/ports/tcpport.js ] and change it until it works for you.

If you succeed please open a pull request adding the port.

**Comment by Ekristoffe** [comment]
indeed i think i need to make a mix between tcpport.js and c701port.js (which use UDP) also why not making a buffered version ...

**Comment by sirockin** [comment]
@Ekristoffe did you get anywhere with this? I'd be happy to collaborate.

**Comment by Ekristoffe** [comment]
Hello all,
Sorry for the long idle time.
I have started to work on it.
I will see what is needed.
BTW what function is needed ?
