### ISSUE TITLE
Use Modbus Tcp connection without intervall

### ISSUE THREAD

**Issue by yadidgarbo** [yaacov/node-modbus-serial#307]
Hi, 
I can't open Tcp Connection then Response of Adress Register and finish Programm with Close Tcp connection in One Shot. 

Don't want to use any settime/set intervall function. Want to get information in one shot. 
``` js
// create an empty modbus client
var ModbusRTU = require("modbus-serial");
var client = new ModbusRTU();

// open connection to a tcp line
client.connectTCP("192.168.1.42");
client.setID(1);

// read the values of 10 registers starting at address 0
// on device number 1. and log the values to the console.
setInterval(function() {
    client.readHoldingRegisters(0, 10, function(err, data) {
        console.log(data.data);
    });
}, 1000);
```

Thanks for help

**Comment by yaacov** [comment]
hi, thank you for the issue.

Here is an example without using `setInterval`:
https://github.com/yaacov/node-modbus-serial/blob/master/examples/simple.js
