### ISSUE TITLE
socket timeout

### ISSUE THREAD

**Issue by vitaly-ignatovich** [yaacov/node-modbus-serial#308]
I successfully ran MODBUS TCP server and client on my PC. If server is running, all works well and client gets response. If server stopped but server port is open, client hangs on reading request forever. Is there an option to set socket timeout on the client?

**Comment by yaacov** [comment]
Hi, thanks for the issue :heart:

did you try `setTimeout` ?
see: https://github.com/yaacov/node-modbus-serial/blob/master/examples/simple.js#L28

**Comment by vitaly-ignatovich** [comment]
Hi Yaacov, 
now working with timeout.
thanks
