### ISSUE TITLE
implement transaction identifier for Modbus/TCP

### ISSUE THREAD

**Issue by valfis86** [yaacov/node-modbus-serial#31]
Modbus/TCP messages contain a "transaction identifier". This field can be used to correlate a modbus response to the request message. 

While sending multiple modbus/TCP requests to a client I faced some issues regarding the length of the expected modbus response ("Data length error, expected ..."). It seems like that you use one field to store the expected length of the answer when sending a new request. This field is overwritten each time a message is send. This leads to errors when sending multiple simultaneous requests with different lengths. 

I was sending a readInputRegisters message directly after sending a writeRegisters message.

**Comment by yaacov** [comment]
Thanks, I will look at it this weekend.
If you can make a pull request, It will be faster.

**Comment by yaacov** [comment]
fixed by #33
