### ISSUE TITLE
How to use this library for Modbus ASCII server over USB COM port

### ISSUE THREAD

**Issue by rohitsay89** [yaacov/node-modbus-serial#318]
Hi I am trying to understand and use this library for Modbus ASCII over serial line (USB to RS-485 converter) for rapid prototyping, I am not able to understand the part where I have to use this library as a Modbus ASCII server over COM port serial line. I mainly see example code for Modbus over TCP but no example of COM port usage for server. It would be great if you can post any example for server part. 

Thanks for your help !
-Rohit

**Comment by yaacov** [comment]
Hi @rohitsay89 , thanks for the issue.

Currently their is no ASCII server, only TCP one:
https://github.com/yaacov/node-modbus-serial/tree/master/servers

You are welcome to implement one and create  a pull request adding it to the library.
