### ISSUE TITLE
How to setup parity and even?

### ISSUE THREAD

**Issue by reejinbouk** [yaacov/node-modbus-serial#32]
Hi
please tell , how to setup even and parity for serial connection?

client.connectRTU("/dev/ttyUSB0", {baudrate: 9600}, write);

like this?
client.connectRTU("/dev/ttyUSB0", {baudrate: 9600, 8e1}, write); - not works

**Comment by yaacov** [comment]
Hi, thanks for the issue see here:
https://github.com/EmergingTechnologyAdvisors/node-serialport#serialport-path-options-opencallback

this should work:
`client.connectRTU("/dev/ttyUSB0", {baudrate: 9600, dataBits: 8, parity: 'even', stopBits: 1}, write);`

**Comment by reejinbouk** [comment]
Thank you! )
