### ISSUE TITLE
readDeviceIdentification fails (ETIMEDOUT) with RTUBuffered, but does work with RTU. I'm reading a array of Tracer solar charge controllers connected via RS485 to USB.

### ISSUE THREAD

**Issue by oicnal** [yaacov/node-modbus-serial#327]
readDeviceIdentification fails (ETIMEDOUT) with RTUBuffered, but does work with RTU. I'm reading a array of Tracer solar charge controllers connected via RS485 to USB.

_Originally posted by @oicnal in https://github.com/yaacov/node-modbus-serial/issues/315#issuecomment-598986786_

**Comment by yaacov** [comment]
hi, thanks for the issue, can you make a pull request adds f43 support to RTUBuffered ?
