### ISSUE TITLE
How to write data to a holding register?

### ISSUE THREAD

**Issue by bluemiaomiao** [yaacov/node-modbus-serial#331]
I want to write the number 0 to the holding register.

**Comment by yaacov** [comment]
hi, thanks for the question :green_heart: 

what did you try, can you post the code ?
what error / unexpected behaviour do you get ?

**Comment by bluemiaomiao** [comment]
I have not encountered any mistakes.
I read the document and found no way to write data to the register, only to send a request and read the data. I want to write the data I have prepared to the register.

**Comment by yaacov** [comment]
did you try:
https://github.com/yaacov/node-modbus-serial/blob/master/examples/write.js

**Comment by bluemiaomiao** [comment]
the code:
```javascript
client.writeRegister(40001, 1);
```

the error:
```
Uncaught (in promise) Error: Modbus exception 2: Illegal data address (register not supported by device)
    at RTUBufferedPort.<anonymous> (D:\modbus-client\node_modules\modbus-serial\index.js:298)
    at emitOne (events.js:116)
    at RTUBufferedPort.emit (events.js:211)
    at RTUBufferedPort._emitData (D:\modbus-client\node_modules\modbus-serial\ports\rtubufferedport.js:108)
    at SerialPort.onData (D:\modbus-client\node_modules\modbus-serial\ports\rtubufferedport.js:71)
    at emitOne (events.js:116)
    at SerialPort.emit (events.js:211)
    at addChunk (_stream_readable.js:263)
    at readableAddChunk (_stream_readable.js:250)
    at SerialPort.Readable.push (_stream_readable.js:208)
```
I want to write the number 1 to the holding register at 40001

**Comment by yaacov** [comment]
> Illegal data address (register not supported by device)

I looks like your device does not support this address.

are you sure it's really 40001 ?
some documentations adds 40000 to denote holding registes, so it they mean *holding register* number 1, they will write *register* 40001. 
you should also note that the first register may be 0 or 1, so you may be looking for register 0 instead of register 1.

**Comment by bluemiaomiao** [comment]
```javascript
client.readHoldingRegisters(0, 8)
```
This is the way I read data to the holding register. I want to write data to this.

**Comment by bluemiaomiao** [comment]
my data:
```javascript
client.readHoldingRegisters(0, 8).then((response) => {let mydata = response.data[1]});
```
This is the way I read data to the holding register. I want to write data to this. How to do it?

**Comment by yaacov** [comment]
for example, starting at address 0: 
https://github.com/yaacov/node-modbus-serial/blob/master/examples/write.js#L40
``` js
client.writeRegisters(0, [10, 9, 8, -20 + 65535, -10 + 65535]);
```

**Comment by yaacov** [comment]
@bluemiaomiao did the example help you ?

**Comment by bluemiaomiao** [comment]
:) thx. @yaacov
