### ISSUE TITLE
Packet length check does not work when reading one coil

### ISSUE THREAD

**Issue by cgoebeler** [yaacov/node-modbus-serial#34]
When trying to read a single coild value from modbus via tcp I receive a "Data length error" originating at the second length check (version 4.4.3 index.js: line 256).

It works as soon as I read multiple coils.

If I comment out the length check the package itself is decoded just fine.

I've tested this with a Codesys Runtime on a Raspberry Pi. Unfortunately I don't have this modbus slave here right now, so I can't paste the actual package content.

**Comment by yaacov** [comment]
Hi, thanks :+1: 

I will not have time to check it until the weekend ... 
If you can find the problem, and make a pull request with a fix It will be great.

cc @meteocontrol

**Comment by cgoebeler** [comment]
Alright, I think I'll have the modbus slave back here later today. Will fix it.

**Comment by yaacov** [comment]
> When trying to read a single coild value from modbus via tcp

What command do you use to read one coil ?

**Comment by cgoebeler** [comment]
I got my modbus slave today and after reinstalling the node module in version 4.4.3 I can not reproduce the issue anymore, also the length check is at a completely different source code location now I seem to have use an older version. Sorry for the inconvenience.

**Comment by yaacov** [comment]
NP :-)
It's good to know new versions are improving ...
We have v4.5.0 now that support the new serial port API
