### ISSUE TITLE
Upgrade to SerialPort v9.0.0 required

### ISSUE THREAD

**Issue by SaikatCool** [yaacov/node-modbus-serial#341]
Hello,

Can this library be updated to use SerialPort v9.0.0.

I am trying to use node-modbus-serial in a ElectronJS app and running into issues.

According to [this](https://github.com/serialport/node-serialport/issues/2031#issuecomment-626324067), the fix is available in SerialPort v9.0.0.

**Comment by yaacov** [comment]
Hello, thanks tor the issue.

Sure, can you make a pull request bumping the version ?

**Comment by SaikatCool** [comment]
@yaacov , pull request on the way.
Only package.json changes fine right?

**Comment by SaikatCool** [comment]
@yaacov , I am not able to push the changes in a new branch. It says access denied.

![image](https://user-images.githubusercontent.com/38331834/83964094-fe804980-a8c7-11ea-998a-75967015d6ce.png)

**Comment by SaikatCool** [comment]
@yaacov  kindly help. I need to get this fixed as soon as possible. Have hit a roadblock :(

**Comment by yaacov** [comment]
to create a pull request on a project you do not have write permission on you need to open a fork:
https://guides.github.com/activities/forking/

once you have a fork you can create a pull request:
https://guides.github.com/activities/forking/#making-a-pull-request

have fun :white_flower:

**Comment by SaikatCool** [comment]
@yaacov thanks for the tip. Still new to using GitHub.

https://github.com/yaacov/node-modbus-serial/pull/342

Could you please check?

**Comment by SaikatCool** [comment]
@yaacov  thanks for approving the pull request.
When the v7.8.2 be published to NPM? so that I can consume it in my project and test.

**Comment by yaacov** [comment]
thanks, merged :green_heart:

**Comment by yaacov** [comment]
https://www.npmjs.com/package/modbus-serial/v/8.0.0

**Comment by SaikatCool** [comment]
Thanks, will test and give you a feedback, @yaacov

**Comment by SaikatCool** [comment]
It works!

Thanks for your good work. Happy to contribute :)

**Comment by SaikatCool** [comment]
@yaacov  could you also please create a tag for v8.0.0? thanks in advance.

**Comment by yaacov** [comment]
sure, have fun
