### ISSUE TITLE
How to get Modbus exception codes

### ISSUE THREAD

**Issue by SaikatCool** [yaacov/node-modbus-serial#345]
Hello,

I am trying to use "node-modbus-serial" to establish communication with a Modbus supported device.

If something goes wrong in the communication, how can I get the corresponding Modbus exception code? The codes mentioned here: https://en.wikipedia.org/wiki/Modbus#Main_Modbus_exception_codes

My plan is to show the appropriate error to the user with an appropriate message so that he can rectify the communication accordingly.

Thanks in advance,

**Comment by sjlongland** [comment]
It's a property on the exception that's thrown.  Look for the `modbusCode` property (a Number).
The message on the exception is usually pretty descriptive too.
