### ISSUE TITLE
custom request

### ISSUE THREAD

**Issue by bechterev** [yaacov/node-modbus-serial#357]
How can I create a custom query or access functions that are not included in the examples? For example, FC 20 - Read file record.

**Comment by yaacov** [comment]
hi, thanks for the question, you can take a look here https://github.com/yaacov/node-modbus-serial/pull/319

**Comment by bechterev** [comment]
I don't quite understand, are you suggesting using FC43/14 instead of FC20 (0x14) or have you added it to the list of future features?

**Comment by yaacov** [comment]
> I don't quite understand, are you suggesting using FC43/14 instead of FC20 (0x14)

no, but you can look at how function code 34 was added and learn how to make a pull request adding support for new function code, then you could make your pull request.

**Comment by bechterev** [comment]
Okay, I'll try.

**Comment by bechterev** [comment]
Не могу понять почему параметр next все время undefined, как его правильно задать. Зацикливается из-за этого параметра. Делаю так
I can't understand why the next parameter is always undefined, and how to set it correctly. Looped because of this parameter. Do so
ModbusRTU.prototype.writeFC20 = function(address, records, length, **next**){

**Comment by bechterev** [comment]
I can't understand why the **next** parameter is always undefined, and how to set it correctly. Looped because of this parameter. Do so
ModbusRTU.prototype.writeFC20 = function(address, records, length, **next**){

**Comment by yaacov** [comment]
`next` is a function that is called when the operation is finished, if it's undefined, no function is called operation is done, if it's a function, the function will be called with relevant parameters

**Comment by bechterev** [comment]
use let f=client.readFileRecords(249, 10).then(x=>console.log(x)).catch(err=>console.log(err));

**Comment by bechterev** [comment]
tell me how to do next not undefined

**Comment by bechterev** [comment]
sorry, I figured it out

**Comment by bechterev** [comment]
I added a function to read the file, but at the end of reading I get the error "illegal data address". How do I get standard error 94?

**Comment by bechterev** [comment]
pr #359
