### ISSUE TITLE
Reading Timed out error

### ISSUE THREAD

**Issue by unocelli** [yaacov/node-modbus-serial#361]
Hi,
I have integrated your library into my project [FUXA ](https://github.com/frangoteam/FUXA).
Not having any hardware I tested with a PC simulator ModRSSim2 and everything works fine.
Now a user has opened a [issue](https://github.com/frangoteam/FUXA/issues/71) where there seems to be a problem by reading values and i don't have much experience with modbus. 

In summary my code works so:
```
this.polling = function () {     // polling function called every 3 seconds
   // read values
   for (var memaddr in mixItemsMap) {
      readVarsfnc.push(client.readInputRegisters(memaddr, ...));
   }
   // check result
   Promise.all(readVarsfnc).then(result => {
      ...
      Exception: Timed out error
   }
```
there are something's wrong in my code?
Thanks

**Comment by skangmy** [comment]
Modbus queries have to be done in a sequential manner. So your current implementation will have issues when your mixItemsMap grows as queries are being run while previous one may still be running.

A better way to do it is to:
1. read input register 1
2. handle query result
3. wait for 50 - 100 ms (duration may vary)
4. repeat step 1 -3 again with next input register

Maybe you can refer to the codes in examples folder to get a better idea on how to do it.

**Comment by unocelli** [comment]
Thanks
