### ISSUE TITLE
Slave Modbus

### ISSUE THREAD

**Issue by reejinbouk** [yaacov/node-modbus-serial#37]
Hello 
does it work in Modbus Slave mode?
please write example?
thank you

**Comment by yaacov** [comment]
Hi, thanks for the question.

What do you mean Modbus Slave mode?

**Comment by reejinbouk** [comment]
Can I make on this library the Modbus Slave device?
I can't find examples for modbus slave, all examples are for modbus master

thank you

**Comment by yaacov** [comment]
This library is only master. 
It can send requests to slaves.
It can not receive requests.

**Comment by reejinbouk** [comment]
ok, thank you

**Comment by yaacov** [comment]
Fixed by https://github.com/yaacov/node-modbus-serial/commit/2435cc8bc3c83ce4d2980fc61516c696da144a8e
