### ISSUE TITLE
How to get data from COM PORT using a web browser

### ISSUE THREAD

**Issue by TheRelow** [yaacov/node-modbus-serial#376]
Hi,
I have not found an example of using data from COM PORT. I tried to do something according to the examples found here, but I get "Unknown error code 3" or "Error: Opening COM1: Access denied"

`
        let serialPort = new serialport(item.pnpId, {baudRate: 9600});
        console.log(serialPort)

        client.open()
            .then((v)=>{
              console.log(v)
            })
            .catch((v)=>{
              console.log(v)
            })
`
For example here comes the error "Unknown error code 3"

**Comment by yaacov** [comment]
Hi, thanks for the issue, can you show a more complete code that create the error ?

**Comment by TheRelow** [comment]
> Hi, thanks for the issue, can you show a more complete code that create the error ?

Ofc

**Comment by yaacov** [comment]
wow, didn't know it works from a browser, only tested with nodejs.

Try using the com name (e.g. "COM1") instead of the actual com object (and make sure it's close before you try to open it for comunication):
`client.connectRTU("COM1", {baudRate: 9600}).then ... // make sure com1 is not open by other user/method `

**Comment by TheRelow** [comment]
> wow, didn't know it works from a browser, only tested with nodejs.
> 
> Try using the com name (e.g. "COM1") instead of the actual com object (and make sure it's close before you try to open it for comunication):
> `client.connectRTU("COM1", {baudRate: 9600}).then ... // make sure com1 is not open by other user/method `

I have tried this connection. But I always get the error "Error: Opening COM4: Access denied"

**Comment by yaacov** [comment]
yes, AFAIU browsers will not let access peripherals without permissions (e.g. camera, disk, serialPort ... )

You will need some way to get access, use some browser extension or library to access the serial port, see:
https://developer.chrome.com/apps/serial
Or build a service that run in the background, see:
https://github.com/yaacov/node-modbus-ws

**Comment by Xsandor** [comment]
@yaacov, I believe your last comment explained both why this is happening and also how TheRelow should move forward. Close issue due to inactivity?
