### ISSUE TITLE
Unit-ID change before read

### ISSUE THREAD

**Issue by biancode** [yaacov/node-modbus-serial#40]
Hi,

is it possible to set the Unit-Id per read/write with the setID function?

**Comment by yaacov** [comment]
a. yes
b. if it doesn't work, we can fix it :-)

**Comment by biancode** [comment]
we will see [node-red-contrib-modbus issue for Unit-Id](https://github.com/biancode/node-red-contrib-modbus/issues/32)

**Comment by biancode** [comment]
I got news that the device sends a Modbus exception 3 - Illegal Data Value - see [node-red-contrib-modbus issue for Unit-Id](https://github.com/biancode/node-red-contrib-modbus/issues/32)

**Comment by biancode** [comment]
works very well
