### ISSUE TITLE
TypeError: Cannot read property 'isOpen' of undefined

### ISSUE THREAD

**Issue by biancode** [yaacov/node-modbus-serial#42]
Hi,

in code I've that:
if (node.client && node.client.isOpen && node.client.isOpen())
to check for close or not

but sometimes: 
TypeError: Cannot read property 'isOpen' of undefined

Idea what's wrong?

**Comment by yaacov** [comment]
i do not think I ever implemented `isOpen` for `ModbusRTU` only for the ports ( e.g. the `._port ` ) ...
but then why does it do work sometimes ... !?

on the other hand I do check for `obj._port.isOpen()` before each send command, so if the `obj._port` is undefined (never opened , or closed) and you try to send something, you can get this error.

**Comment by yaacov** [comment]
fixed by https://github.com/yaacov/node-modbus-serial/pull/49
