### ISSUE TITLE
isOpen() not working

### ISSUE THREAD

**Issue by timothycuenat-lam** [yaacov/node-modbus-serial#441]
Hello,
I don't know if it's me or not, but i think that the isOpen() on TCP connection is not working.
First it is not a function but a boolean variable and for all the tests I made, it is always set at FALSE.

It would be nice if it could work.
It could be even better if we could register an event at the connect function. It could alert us when the connection is lost.

Otherwise it's cool, thanks

**Comment by pmb0** [comment]
It‘s `isOpen` and not `isOpen()`. Working here.
