### ISSUE TITLE
Modbus request in response

### ISSUE THREAD

**Issue by biancode** [yaacov/node-modbus-serial#46]
A [feature request](https://github.com/biancode/node-red-contrib-modbus/issues/3) needs an enhancement of the response to have data, response and request buffer, please

response {
 request: Buffer with CRC
 data : []
 buffer: Buffer
}

That is a good idea for debugging

**Comment by yaacov** [comment]
hi,

can you try to take:
https://github.com/yaacov/node-modbus-serial/blob/master/ports/rtubufferedport.js
copy it call it debug port.

then add an emiter for `debug` messages , e.g.
when reciving data [line 72]
`this.emit('debug', this._buffer.slice(start, start + length));`
and when sending data [line 136]
`this.emit('debug', data);`

I am a little busy with other things, so if you will wait for me, it can take some time,
I think that this new debug port will do the trick :-)

**Comment by yaacov** [comment]
fixed by #50 and #51

**Comment by yaacov** [comment]
@connium @biancode hi,

Looking at the  [debug](https://www.npmjs.com/package/debug) module I only see the options to send to stdout/file.
Can we solve this issue using  [debug](https://www.npmjs.com/package/debug) module or some other standard way ?

**Comment by biancode** [comment]
I'll try some more next week.

**Comment by biancode** [comment]
for me yes - debug is perfect - but there is no debug output for now - right?  DEBUG=*  or DEBUG=modbus-serial doesn't work

**Comment by connium** [comment]
You are right, there are no debug outputs in the code yet. Will add them in the upcoming week (I'm missing them sometimes as well :wink: ).

**Comment by yaacov** [comment]
> I'm missing them sometimes as well 😉

👍

**Comment by biancode** [comment]
node-red-contrib-modbus is working with debug npm from version 1.0.6+ and using the name 
`DEBUG=modbus-serial `
for modbus info and otherwise with the name 
`DEBUG=node_red_contrib_modbus`
