### ISSUE TITLE
fail on tsc buid with version 8.0.7

### ISSUE THREAD

**Issue by dbettoni** [yaacov/node-modbus-serial#482]
On last version 8.0.7 my tsc build produce this error:
> tsc

node_modules/modbus-serial/ModbusRTU.d.ts:2:22 - error TS7016: Could not find a declaration file for module './ports/testport'. '...../node_modules/modbus-serial/ports/testport.js' implicitly has an 'any' type.

2 import TestPort from './ports/testport';

8.0.6 is OK

**Comment by yaacov** [comment]
Hi, thanks for the issue :fire:

Can you make a pull request fixing it ?

**Comment by dbettoni** [comment]
I can try but I don't know when or time to do it,
for now the project works by setting the dependency to "modbus-serial": "8.0.6",

**Comment by yaacov** [comment]
The issue looks related to https://github.com/yaacov/node-modbus-serial/pull/479
@chaos2171053 hi, can you take a look ?

@dbettoni can you add more information that will help understand the problem, link to your code ?
for example:
how you use the module in your project ?
how do you get the error ?

**Comment by chaos2171053** [comment]
> On last version 8.0.7 my tsc build produce this error:
> 
> > tsc
> 
> node_modules/modbus-serial/ModbusRTU.d.ts:2:22 - error TS7016: Could not find a declaration file for module './ports/testport'. '...../node_modules/modbus-serial/ports/testport.js' implicitly has an 'any' type.
> 
> 2 import TestPort from './ports/testport';
> 
> 8.0.6 is OK

fix on this [pr](https://github.com/yaacov/node-modbus-serial/pull/484#issue-1467366277) .Can u provie more information to repoduce this bug?May be i can make this pr better.

**Comment by yaacov** [comment]
#484 is merged @dbettoni can you check the fix ?

**Comment by dbettoni** [comment]
I tried to rebuild my project by importing modbus-serial 8.0.7 but the problem hasn't been resolved.
see attached image
<img width="2064" alt="Schermata 2022-11-29 alle 12 44 47" src="https://user-images.githubusercontent.com/30083487/204521922-09b08323-e5c1-4757-8da0-39b8618278b1.png">

**Comment by dbettoni** [comment]
my tsconfig.json:
<img width="376" alt="Schermata 2022-11-29 alle 14 14 22" src="https://user-images.githubusercontent.com/30083487/204538782-25ba7087-bb0a-482f-b803-82e18c8d61cf.png">

**Comment by yaacov** [comment]
@dbettoni hi, 8.0.7 does not have the fix, it will be in 8.0.8, can you test the code from github ?

**Comment by chaos2171053** [comment]
> I tried to rebuild my project by importing modbus-serial 8.0.7 but the problem hasn't been resolved. see attached image <img alt="Schermata 2022-11-29 alle 12 44 47" width="2000" src="https://user-images.githubusercontent.com/30083487/204521922-09b08323-e5c1-4757-8da0-39b8618278b1.png">

Hi @dbettoni ,version 8.0.7 has not inclued the #484 ,you can use `npm install "https://github.com/yaacov/node-modbus-serial#master ---save` to use the latest code. 

[Install specific branch from github using Npm](https://stackoverflow.com/questions/39732397/install-specific-branch-from-github-using-npm)](https://stackoverflow.com/questions/39732397/install-specific-branch-from-github-using-npm)


@yaacov how about adding github ci scripts to publish the latest code to npm when pr is merged to the master or specific branch ?

**Comment by yaacov** [comment]
> @yaacov how about adding github ci scripts to publish the latest code to npm when pr is merged to the master or specific branch ?

an action that publish on new release will be nice :-) 
but this fix will need the npm secret, I can look at a PR that assume an npm secret exist, and add the needed secret

**Comment by dbettoni** [comment]
perfect, with the "modbus-serial" dependency: "git+https://github.com/yaacov/node-modbus-serial.git#master", everything is OK
Thanks for all

**Comment by yaacov** [comment]
8.0.8 is release :cake:

**Comment by dbettoni** [comment]
OK Thanks
