### ISSUE TITLE
Latest version does not compile?

### ISSUE THREAD

**Issue by AuspeXeu** [yaacov/node-modbus-serial#524]
![image](https://github.com/yaacov/node-modbus-serial/assets/2115696/6dbe96c9-303d-49aa-a6d5-e2de35bde8d2)

**Comment by yaacov** [comment]
Thank you for the issue !

can you fix the d.ts file ?

**Comment by AuspeXeu** [comment]
Don't know how, sorry :(

**Comment by yaacov** [comment]
@AuspeXeu hi, can you test the fixes in #525 ?

**Comment by yaacov** [comment]
https://www.npmjs.com/package/modbus-serial/v/8.0.15 :tada: :cake:

**Comment by yaacov** [comment]
p.s.
@AuspeXeu can you write a test that will fail on bad `d.ts` files ?

**Comment by AuspeXeu** [comment]
Seems fixed, thanks! :)
