### ISSUE TITLE
Why is the npm package name modbus-serial?

### ISSUE THREAD

**Issue by Shashank5665** [yaacov/node-modbus-serial#527]
Hi there,
I know this may be a weird question, but why is the npm package name modbus-serial ?
When I first saw the package name, I though it would not support TCP/IP. Then I went on to see some other packages.
When it supports TCP/IP, please generalize the npm package name, maybe like "modbus-node" or something general.

**Comment by yaacov** [comment]
thank you for the issue :green_heart: 

the name issue makes sense, but changing a package name is problematic,
how do we make sure people already using the package will know it's name changed ?
how dowe make sure links pointing to the package (and code) will continue working ?
