### ISSUE TITLE
Port Not Open

### ISSUE THREAD

**Issue by vinit21** [yaacov/node-modbus-serial#529]
TCP Logger  - 

I am pooling 10 modbus devices every 3 seconds. It works well for first 3 minutes and then end up with port not open error. Please find the screen shot of the time where it stopped working. 

When it is working - it is just a beautiful piece of software. I am super grateful to the team for keeping it so updated.  Pooling is faster than kepware. Is there any way we can donate to the team. 

<img width="405" alt="image" src="https://github.com/yaacov/node-modbus-serial/assets/57453237/4031fa35-2ec7-4246-b005-c501f8bba1c5">

**Comment by yaacov** [comment]
hi, thank you for the issue

adding a help wanted label, in case someone is having the same issue and can help.

look at the examples directory, here is an example that handle errors that should recover from errors:
https://github.com/yaacov/node-modbus-serial/blob/master/examples/logger_complete.js

**Comment by vinit21** [comment]
I found the error. Lib is perfectly working. 
It was a silly mistake from my end. Sorry for the trouble.

**Comment by IlCallo** [comment]
@vinit21 can you share which was your mistake?
Cause I'm getting the same behavior and I may be doing the same one
