### ISSUE TITLE
Destroy function callback never to be called

### ISSUE THREAD

**Issue by narttmk** [yaacov/node-modbus-serial#541]
![image](https://github.com/yaacov/node-modbus-serial/assets/28924284/761b0c0e-bc99-4f9d-b424-1abe238d324c)
this._port.destroy function is received an Error instance, so in this case callback never to be called

**Comment by yaacov** [comment]
Hi, thank you for the issue.

Q. does the `callback` get called ?

Can you investigate the reason for this issue, and suggest a fix ?

Ref:
https://github.com/yaacov/node-modbus-serial/blob/master/index.js#L684

**Comment by narttmk** [comment]
Hi yaacov, 
A: callback does not get called. 
Because SerialPortStream extend stream.Duplex
Ref: 
https://github.com/serialport/node-serialport/blob/main/packages/stream/lib/index.ts#L70
https://nodejs.org/api/stream.html#class-streamduplex

So the arg push into destroy function should be array of Error. 
I suggest that we should move callback to next line below destroy
![image](https://github.com/yaacov/node-modbus-serial/assets/28924284/35fb74f6-66ad-45e9-a2c1-394f5ee96eb6)

**Comment by yaacov** [comment]
nice, can you make a pull request ?

**Comment by narttmk** [comment]
Sure, I created a PR, please help me to review and merge it
https://github.com/yaacov/node-modbus-serial/pull/542
