### ISSUE TITLE
TCP reconnect doesn't work

### ISSUE THREAD

**Issue by biancode** [yaacov/node-modbus-serial#64]
Hi,

since v4.6.1 (also 5.1.3) there is no error on lost TCP connection. How can I get that info from modbus-serial? Error is empty in that case. ( err{} )

before it raises the err.code === 'ECONNRESET' -  see with 4.5.1 it works

**Comment by yaacov** [comment]
can you try to use promise on the command that trigger the error ? [ e.g. `.catch(function(err) { ... } )` ]

**Comment by biancode** [comment]
I'm using these tow events:
    
```
node.client._port.on('close', node.onModbusClose)
node.client._port.on('error', node.onModbusError)
```

**Comment by yaacov** [comment]
we already catch the `node.client._port.on('error' ...` here:
https://github.com/yaacov/node-modbus-serial/blob/master/ports/tcpport.js#L70
maybe the promise `.catch(...` syntex will catch more errors ?

**Comment by biancode** [comment]
also in catch empty -> modbus-serial {} +1s

**Comment by yaacov** [comment]
> also in catch

hmm.... i will look into it more carefully ( probably next weekend )

**Comment by biancode** [comment]
it would be great to have the Why it is not open as before - Connection Error or Reset or ... as TCP sends

**Comment by biancode** [comment]
err.code I used before

**Comment by yaacov** [comment]
we can not get an error from the `tcpport` for sending data to a close port because of this:
https://github.com/yaacov/node-modbus-serial/blob/master/index.js#L602

but we can change the error code, will setting the error code to <SOMETHING> be ok ?

**Comment by yaacov** [comment]
> it would be great to have the Why it is not open as before - Connection Error or Reset or ... as TCP sends

You should also get this from a `.catch` on the `connectTCP` see:
https://github.com/yaacov/node-modbus-serial/blob/master/examples/simple.js#L8

**Comment by biancode** [comment]
.catch works for me this way:  first I got Time out - plugged off the cable on working device - then later I got Port Not Open - net should tell you error 'ECONNRESET'

**Comment by biancode** [comment]
possible codes - https://gist.github.com/gabrielfalcao/4216897

**Comment by yaacov** [comment]
who is sending the errors: 
the `.catch ` is on the read/write command or the `.catch` on the `connectTCP` ?
the one on the  `connectTCP` should return the correct tcp error ... I will have to look into it ...

**Comment by biancode** [comment]
.catch on read/write - connection is well done and then I unplug the device

**Comment by biancode** [comment]
OK, now I got it to work very well.

`if(err.errno)`

then I can check the strings - errno is filled up in err object if we have a tcp error

`var networkErrors = ['ESOCKETTIMEDOUT', 'ETIMEDOUT', 'ECONNRESET', 'ECONNREFUSED'];`

**Comment by yaacov** [comment]
Can you give more info ... how to get this error ? where to put the `err.errno` check ? what port do you use ... ? do yo you know what fixed the problem ? ...

**Comment by biancode** [comment]
There is no real fix - just more information in debugging - I just checked for ECONNRESET and the special case was ETIMEDOUT, if it doesn't reconnect
if the error comes from the TCP Socket, then I got the errno in error object - see new pull request examples - it was all fine with the promises and the use of .catch

**Comment by yaacov** [comment]
👍 Nice :-)

**Comment by srinivasyl** [comment]
I'm able to ping IP of Modbus PLC but, I'm not able to connect from the following script

```
var ModbusRTU = require("modbus-serial");
var client = new ModbusRTU();

client.connectTCP("192.168.9.2", { port: 502 });
client.setID(1);
 
setInterval(function() {
    client.readHoldingRegisters(3,1, function(err, data) {
        console.log(data);
    });
}, 1000);
```

the script throws the following error
" UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: connect ECONNREFUSED 192.168.9.2:502"

help me to solve this error

**Comment by yaacov** [comment]
Hi, @srinivasyl , can you try connect using some other tool ?
Maybe your device listen on some other port ? maybe your device does not answer to read holding registers, it can be many things ...

**Comment by srinivasyl** [comment]
I've used Modbus pal simulator 
if I run Modbus pal in my system(IP: 127.0.0.1, PORT:502) the script was able to connect, read and write to registers but, If Modbus pal is running in the different machine it, then the script was unable to connect.
Is that network issue?

**Comment by yaacov** [comment]
> Is that network issue?

try connect with the script from local machine ( like you did with the pal simulator ), if it also works, then it is probably network issue.
