### ISSUE TITLE
Wiki instead README

### ISSUE THREAD

**Issue by biancode** [yaacov/node-modbus-serial#75]
We should clean up the README with most important information and refer to the Wiki for more details and examples.

**Comment by yaacov** [comment]
👍 

first stage copy the readme to the wiki ?

**Comment by yaacov** [comment]
I copied the readme to the wiki ... feel free to do whatever you think helpful, 
I have no idea what to do next :-)

**Comment by biancode** [comment]
done for me with your work and my [Pull request](https://github.com/yaacov/node-modbus-serial/pull/76)
