### ISSUE TITLE
writeFC15 outputs wrong values

### ISSUE THREAD

**Issue by connium** [yaacov/node-modbus-serial#9]
When writing several coils (count other than 8), the respecting byte is expected to be filled with zeros.

E.g. writing 5 coils (true, true, true, true, true) should result in 0x1F (0001 1111).

The current implementation does not explicitly write the zeros but stops after writing the 5 bits. This may result in unexpected values as the used byte may still contain bits (other than 0).

**Comment by yaacov** [comment]
Thanks, you are right !
https://github.com/yaacov/node-modbus-serial/commit/a01f8516ea0b16117c9aee8f340932cf8b4a3f9f

**Comment by connium** [comment]
You're damn fast! Thanks. :thumbsup:

**Comment by yaacov** [comment]
Next time, just do the pull request I will not have time :-)
