### ISSUE TITLE
Wrte Only - Broad cast

### ISSUE THREAD

**Issue by inpras** [yaacov/node-modbus-serial#97]
Is there any way to configure RTU Buffered to have write only request (as in broadcast request)?

**Comment by yaacov** [comment]
What happen when you try, it should just work ?

**Comment by inpras** [comment]
This is the code I have

```
client.writeRegister(currentParameter.mbAddress, currentParameter.value, function(err, data) {
                    if (!err){
                    } else {
                    }
                });
```

the call for writeRegister stays there forever, never comes out! I think it is expecting reply from slave device and for broadcast messages, we don't get reply!

**Comment by yaacov** [comment]
what happen when you do not try to catch the error ?
e.g. `client.writeRegister(currentParameter.mbAddress, currentParameter.value)`

**Comment by inpras** [comment]
No change with that also. There is a promise that keeps waiting if the callback is not supplied.

**Comment by yaacov** [comment]
> There is a promise that keeps waiting if the callback is not supplied.

Yes, but a promise does not block, you can continue to use the port for other requests and ignore the waiting promise.

**Comment by inpras** [comment]
OK, let me give a try to see what I was missing earlier, thank you for your response. Will get back to you with my results.

**Comment by yaacov** [comment]
p.s. 
low level commands, can be called without a callback, e.g.
`client.writeFC6(currentParameter.mbAddress, currentParameter.value)`

**Comment by inpras** [comment]
yes, that makes more informed of me. Thank you

**Comment by yaacov** [comment]
np :-)

If this works, you can close the issue, if not, comment here.

**Comment by inpras** [comment]
Thank you this would fit my need. I am closing this now.

**Comment by jjailbird** [comment]
thanks
